/*! jQuery Browser - v0.1.0 - 3/23/2012
* https://github.com/jquery/jquery-browser
* Copyright (c) 2012 John Resig; Licensed MIT */
/* Modernizr 2.5.3 (Custom Build) | MIT & BSD
 * Build: http://www.modernizr.com/download/#-csstransforms3d-prefixed-teststyles-testprop-testallprops-prefixes-domprefixes
 */
/*!
 * jQuery hashchange event - v1.3 - 7/21/2010
 * http://benalman.com/projects/jquery-hashchange-plugin/
 * 
 * Copyright (c) 2010 "Cowboy" Ben Alman
 * Dual licensed under the MIT and GPL licenses.
 * http://benalman.com/about/license/
 */
/*
 * @name wowBook
 *
 * @author Marcio Aguiar
 * @version 1.0
 * @requires jQuery v1.7.0
 *
 * Copyright 2010 Marcio Aguiar. All rights reserved.
 *
 * To use this file you must to buy a licence at http://codecanyon.net/user/maguiar01/portfolio
 *
 * Date: Wed Dec 8 10:05:49 2010 -0200
 */
(function(d){if(!d.browser){var r;r=navigator.userAgent||"";d.uaMatch=function(d){d=d.toLowerCase();d=/(chrome)[ \/]([\w.]+)/.exec(d)||/(webkit)[ \/]([\w.]+)/.exec(d)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(d)||/(msie) ([\w.]+)/.exec(d)||0>d.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(d)||[];return{browser:d[1]||"",version:d[2]||"0"}};r=d.uaMatch(r);d.browser={};r.browser&&(d.browser[r.browser]=!0,d.browser.version=r.version);d.browser.webkit&&(d.browser.safari=!0)}})(jQuery);
window.Modernizr=function(d,r,t){function u(a,c){for(var e in a)if(b[a[e]]!==t)return"pfx"==c?a[e]:!0;return!1}function k(a,b,e){var d=a.charAt(0).toUpperCase()+a.substr(1),g=(a+" "+c.join(d+" ")+d).split(" ");if("string"===typeof b||"undefined"===typeof b)b=u(g,b);else{g=(a+" "+f.join(d+" ")+d).split(" ");a:{a=g;for(var h in a)if(d=b[a[h]],d!==t){b=!1===e?a[h]:"function"===typeof d?d.bind(e||b):d;break a}b=!1}}return b}var l={},m=r.documentElement,a=r.createElement("modernizr"),b=a.style;d=" -webkit- -moz- -o- -ms- ".split(" ");
var c=["Webkit","Moz","O","ms"],f=["webkit","moz","o","ms"],a={},e=[],g=e.slice,j,h=function(a,b,c,e){var f,d,g,h=r.createElement("div"),j=r.body,v=j?j:r.createElement("body");if(parseInt(c,10))for(;c--;)g=r.createElement("div"),g.id=e?e[c]:"modernizr"+(c+1),h.appendChild(g);return f=["&#173;<style>",a,"</style>"].join(""),h.id="modernizr",(j?h:v).innerHTML+=f,v.appendChild(h),j||(v.style.background="",m.appendChild(v)),d=b(h,a),j?h.parentNode.removeChild(h):v.parentNode.removeChild(v),!!d},s={}.hasOwnProperty,
v;"undefined"!==typeof s&&"undefined"!==typeof s.call?v=function(a,b){return s.call(a,b)}:v=function(a,b){return b in a&&"undefined"===typeof a.constructor.prototype[b]};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;var c=g.call(arguments,1),e=function(){if(this instanceof e){var f=function(){};f.prototype=b.prototype;var f=new f,d=b.apply(f,c.concat(g.call(arguments)));return Object(d)===d?d:f}return b.apply(a,c.concat(g.call(arguments)))};
return e});var x=[,"csstransforms3d"],n=[,["@media (",d.join("transform-3d),("),"modernizr){#csstransforms3d{left:9px;position:absolute;height:3px;}}"].join("")].join(""),q=x.length;h(n,function(a){a=a.childNodes;for(var b={};q--;)b[a[q].id]=a[q];l.csstransforms3d=9===(b.csstransforms3d&&b.csstransforms3d.offsetLeft)&&3===b.csstransforms3d.offsetHeight},q,x);a.csstransforms3d=function(){var a=!!k("perspective");return a&&"webkitPerspective"in m.style&&(a=l.csstransforms3d),a};for(var p in a)v(a,p)&&
(j=p.toLowerCase(),l[j]=a[p](),e.push((l[j]?"":"no-")+j));b.cssText="";return a=null,l._version="2.5.3",l._prefixes=d,l._domPrefixes=f,l._cssomPrefixes=c,l.testProp=function(a){return u([a])},l.testAllProps=k,l.testStyles=h,l.prefixed=function(a,b,c){return b?k(a,b,c):k(a,"pfx")},l}(this,this.document);
(function(d,r,t){function u(a){a=a||location.href;return"#"+a.replace(/^[^#]*#?(.*)$/,"$1")}"$:nomunge";var k=document,l,m=d.event.special,a=k.documentMode,b="onhashchange"in r&&(a===t||7<a);d.fn.hashchange=function(a){return a?this.bind("hashchange",a):this.trigger("hashchange")};d.fn.hashchange.delay=50;m.hashchange=d.extend(m.hashchange,{setup:function(){if(b)return!1;d(l.start)},teardown:function(){if(b)return!1;d(l.stop)}});var c=function(){var a=u(),b=j(e);a!==e?(g(e=a,b),d(r).trigger("hashchange")):
b!==e&&(location.href=location.href.replace(/#.*/,"")+b);f=setTimeout(c,d.fn.hashchange.delay)},m={},f,e=u(),g=a=function(a){return a},j=a;m.start=function(){f||c()};m.stop=function(){f&&clearTimeout(f);f=t};if(d.browser.msie&&!b){var h,s;m.start=function(){h||(s=(s=d.fn.hashchange.src)&&s+u(),h=d('<iframe tabindex="-1" title="empty"/>').hide().one("load",function(){s||g(u());c()}).attr("src",s||"javascript:0").insertAfter("body")[0].contentWindow,k.onpropertychange=function(){try{"title"===event.propertyName&&
(h.document.title=k.title)}catch(a){}})};m.stop=a;j=function(){return u(h.location.href)};g=function(a,b){var c=h.document,e=d.fn.hashchange.domain;a!==b&&(c.title=k.title,c.open(),e&&c.write('<script>document.domain="'+e+'"\x3c/script>'),c.close(),h.location.hash=a)}}l=m})(jQuery,this);
(function(d){function r(a,b){a=d(a);var c=this;this.elem=a;this.id=a.attr("id");this.pages=[];this.opts=b;this.currentPage=null;this.pageWidth=b.width/2;this.pageHeight=b.height;this.transparentPages=b.transparentPages=!1;this.startPage=b.startPage;this.onShowPage=b.onShowPage;this.slideShow=b.slideShow;this.slideShowDelay=b.slideShowDelay;this.pauseOnHover=b.pauseOnHover;this.turnPageDuration=b.turnPageDuration;this.foldGradient=b.foldGradient;this.foldGradientThreshold=b.foldGradientThreshold;this.shadows=
b.shadows;this.shadowThreshold=b.shadowThreshold;this.clipBoundaries=b.clipBoundaries;this.zoomLevel=b.zoomLevel;this.zoomMax=b.zoomMax;this.zoomMin=b.zoomMin;this.zoomBoundingBox=b.zoomBoundingBox;this.zoomStep=b.zoomStep;this.onZoom=b.onZoom;this.mouseWheel=b.mouseWheel;this.flipSound=b.flipSound;this.centeredWhenClosed=b.centeredWhenClosed;this.sectionDefinition=b.sections;d.wowBook.support.filters="filters"in a[0];a.addClass("wowbook");"static"===a.css("position")&&a.css("position","relative");
var f=a.children(),e=this.pagesContainer=this.origin=d("<div class='wowbook-origin'></div>").css({position:"absolute"}).appendTo(a);c.bookShadow=d("<div class='wowbook-book-shadow'></div>").appendTo(a).css({top:0,position:"absolute",display:"none",zIndex:0});this.insertPages(f,!0);e.append("<div class='wowbook-shadow-clipper'><div class='wowbook-shadow-container'><div class='wowbook-shadow-internal'></div></div></div>");c.shadowContainer=d(".wowbook-shadow-container",e);c.internalShadow=d(".wowbook-shadow-internal",
e);c.shadowClipper=d(".wowbook-shadow-clipper",e).css({display:"none"});c.foldShadow=d("<div class='wowbook-shadow-fold'></div>").appendTo(c.shadowContainer);c.foldGradientContainer=d("<div class='wowbook-fold-gradient-container'></div>").appendTo(c.shadowContainer);c.foldGradientElem=d("<div class='wowbook-fold-gradient'></div>").appendTo(c.foldGradientContainer);c.hardPageShadow=d("<div class='wowbook-hard-page-shadow'></div>").css({display:"none"}).appendTo(e);!d.support.opacity&&d.wowBook.support.filters&&
d.wowBook.applyAlphaImageLoader(["wowbook-fold-gradient","wowbook-fold-gradient-flipped","wowbook-shadow-fold","wowbook-shadow-fold-flipped"]);c.shadowContainer.css("position","relative");this.leftHandle=d("<div class='wowbook-handle wowbook-left'></div>").data("corner","l").appendTo(e);this.rightHandle=d("<div class='wowbook-handle wowbook-right'></div>").data("corner","r").appendTo(e);Modernizr.csstransforms3d&&(f=d("<div>").css("transform","perspective(1px)"),this.perspectiveUnit="none"!=f.css("transform")?
"px":"",f=null);d.browser.msie&&d(".wowbook-handle",a).css({backgroundColor:"#fff",opacity:"0.01"});d(".wowbook-handle",e).bind("mousedown",function(a){return c.pageEdgeDragStart(a)});b.curl&&d(".wowbook-handle",e).hover(function(a){var b=this==c.leftHandle[0]?c.leftPage():c.rightPage();if(b){var e=b.offset();c.curl(b,a.pageY-e.top>c.pageHeight/2)}},function(){c.uncurl()});var g;d(".wowbook-handle",e).mousedown(function(){g=d.now()}).mouseup(function(){if(!((new Date).getTime()-g>c.opts.handleClickDuration)){var a=
d(this).data("corner");"r"===a&&c.advance();"l"===a&&c.back()}});var j=!1;a.hover(function(){if(c.pauseOnHover){j=c.slideShowTimer;var a=d(c.opts.controls.slideShow),b=a.hasClass("wowbook-disabled");c.stopSlideShow();a.toggleClass("wowbook-disabled",b)}},function(){c.pauseOnHover&&j&&c.startSlideShow()});this.clipBoundaries&&(this.origin.wrap("<div class='wowbook-clipper'><div class='wowbook-inner-clipper'></div></div>"),d(".wowbook-inner-clipper",a).css({position:"absolute",width:"100%",overflow:"hidden"}),
this.clipper=d(".wowbook-clipper",a).css({position:"absolute",left:0,top:0,width:"100%",overflow:"hidden",zIndex:1}));a.wrapInner("<div class='wowbook-zoomwindow'><div class='wowbook-zoomcontent'></div></div>");this.zoomWindow=d(".wowbook-zoomwindow",a);this.zoomContent=d(".wowbook-zoomcontent",a);d.browser.ie8mode&&this.zoomContent.wrapInner("<div class='IE8-zoom-helper'style='position:relative'></div>");this.zoomWindow.css({position:"absolute",top:0});this.zoomContent.css({position:"absolute",left:0,
top:0});this.setDimensions(this.opts.width,this.opts.height);this.fillToc();if(b.deepLinking&&this.getLocationHash()){var h;try{h=c.selectorToPage("#"+this.getLocationHash())}catch(s){}void 0===h&&(h=c.locationHashToPage());"number"===typeof h&&(c.startPage=h,u(c.elem)||c.elem[0].scrollIntoView())}this.flipSound&&(this.audio=this.createAudioPlayer());this.opts.keyboardNavigation&&d(document).keydown(function(a){d(a.target).filter("input, textarea, select").length||(a.which===c.opts.keyboardNavigation.back&&
c.back(),a.which===c.opts.keyboardNavigation.advance&&c.advance())});d(window).hashchange(function(){var a=window.location.hash;if(a===c.locationHashSetTo)c.locationHashSetTo=void 0;else{var b=(a=""===a&&!c.locationEndsInHash())?c.startPage:c.locationHashToPage();"number"===typeof b&&(c.gotoPage(b,!a),!a&&!u(c.elem)&&c.elem[0].scrollIntoView())}});b.forceBasicPage&&(this.foldPage=this.holdHardpage=this.foldPageBasic);d.wowBook.support.transform||(this.foldPage=this.foldPageBasic,d.wowBook.support.filters||
(this.holdHardpage=this.foldPageBasic));this.mouseWheel&&a.mousewheel(function(a,b){if(c.mouseWheel)return"zoom"===c.mouseWheel?(0<b&&c.zoomIn(),0>b&&c.zoomOut(),c.zoomedAt(a)):(0<b&&c.advance(),0>b&&c.back()),!1});this.touchSupport();this.controllify(this.opts.controls);this.opts.thumbnails&&this.createThumbnails();this.showPage(this.startPage,!1);b.slideShow&&this.startSlideShow()}function t(a,b){var c=Math.cos(b),f=Math.sin(b);return{x:c*a.x-f*a.y,y:f*a.x+c*a.y}}function u(a){var b=d(window).height(),
c=a.offset(),f=d(window).scrollTop();return c.top>f&&c.top+a.height()<f+b}function k(a,b,c){var f,e,g,j;f=e=0;if(!d.wowBook.support.boxSizing){var h;f="none"==a.css("borderTopStyle")?0:m[h=a.css("borderTopWidth")]||parseFloat(h);e="none"==a.css("borderRightStyle")?0:m[h=a.css("borderRightWidth")]||parseFloat(h);g="none"==a.css("borderBottomStyle")?0:m[h=a.css("borderBottomWidth")]||parseFloat(h);j="none"==a.css("borderLeftStyle")?0:m[h=a.css("borderLeftWidth")]||parseFloat(h);e=parseFloat(a.css("paddingLeft"))+
parseFloat(a.css("paddingRight"))+j+e;f=parseFloat(a.css("paddingTop"))+parseFloat(a.css("paddingBottom"))+f+g}a.css("width",b-e);a.css("height",c-f)}d.wowBook=function(a){return d(a).data("wowBook")};d.wowBook.support={};d.fn.wowBook=function(a){if("string"===typeof a){var b=Array.prototype.slice.call(arguments,1);if("options"===a||"prop"===a){var c=d.wowBook(this[0]),f=b[0];return 1<b.length?c[f]=b[1]:c[f]}return this.each(function(){var c=d.wowBook(this);c[a].apply(c,b)})}var e=d.extend({},d.wowBook.defaults,
a);return this.each(function(){var a=new r(this,e);d(this).data("wowBook",a)})};r.prototype={setDimensions:function(a,b){var c=this.elem;this.pageWidth=a/2;this.pageHeight=b;c.css({height:b,width:a});var f=c.height(),e=this.origin.css({width:"100%",height:f});this.bookShadow.css({width:a,height:b});for(var g,j=!1,h=0,s=this.pages.length;h<s;h++)this.pages[h].css({width:this.pageWidth,height:this.pageHeight,left:j?0:this.pageWidth}),j=!j,g=d(".wowbook-page-content",this.pages[h]),k(g,this.pageWidth,
this.pageHeight);this.opts.gutterShadow&&d(".wowbook-gutter-shadow",c).css("height",this.pageHeight);this.positionBookShadow();this.shadowClipper.css({width:c.width(),height:f});this.hardPageShadow.css({width:this.pageWidth,height:this.pageHeight});this.opts.handleWidth&&d(".wowbook-handle",e).css("width",this.opts.handleWidth);this.rightHandle.css("left",a-this.rightHandle.width());this.clipBoundaries&&(e=Math.sqrt(this.pageWidth*this.pageWidth+this.pageHeight*this.pageHeight),e=[this.pageHeight-
e,c.width(),e,0],this.origin.css("top",-e[0]),d(".wowbook-inner-clipper",c).css({width:"100%",height:e[2]-e[0],top:e[0]}),this.clipper.css({width:"100%",height:f}));this.zoomWindow.css({width:2*this.pageWidth,height:f});this.zoomContent.css({width:2*this.pageWidth,height:f});this.corners={tl:[0,0],bl:[0,this.pageHeight],tr:[this.pageWidth,0],br:[this.pageWidth,this.pageHeight],l:[0,0],r:[this.pageWidth,0]}},resize:function(a,b){this.setDimensions(a,b)},resizeToFit:function(a,b){var c=2*this.pageWidth/
this.pageHeight;b*c<=a?a=b*c:b=a/c;this.resize(a,b)},insertPages:function(a,b){for(var c=0,f=a.length;c<f;c++)this.insertPage(a[c],!0);this.updateBook(b)},insertPage:function(a,b){a=d(a).addClass("wowbook-page-content");var c=d("<div class='wowbook-page'></div>").css({width:this.pageWidth,height:this.pageHeight,display:"none",position:"absolute"}).appendTo(this.pagesContainer).append(a);d.wowBook.support.boxSizing&&a.css(d.wowBook.support.boxSizing,"border-box");k(a,this.pageWidth,this.pageHeight);
c.hardPageSetByUser=a.hasClass("wowbook-hardpage");this.opts.gutterShadow&&d("<div class='wowbook-gutter-shadow'></div>").appendTo(a).css("height",this.pageHeight);this.pages.push(c);b||this.updateBook();return c},removePages:function(a,b){arguments.length||(a=0,b=-1);this.holdedPage&&this.releasePage(this.holdedPage);var c=this.pages;b=(b||a)+1||c.length;var f=c.slice(a,b),e=c.slice(b);c.length=0>a?c.length+a:a;c.push.apply(c,e);for(var e=0,d=f.length;e<d;e++)f[e].remove();this.updateBook();return c.length},
updateBook:function(a){this.doPageNumbering();this.findPagesType();this.positionBookShadow();for(var b=!1,c,f=0,e=this.pages.length;f<e;f++)c=this.pages[f].toggleClass("wowbook-left",b).toggleClass("wowbook-right",!b).data({pageIndex:f,holded:!1}),c.pageIndex=f,b=!b;this.findSections();a||this.showPage(this.currentPage)},doPageNumbering:function(){var a=this.opts;if(a.pageNumbers){var b=a.numberedPages,a=this.pages.length-1,c=this.pageIsOnTheLeft(a);"all"==b&&(b=[0,-1]);b||(b=[2,c?-3:-2]);var f=b[0],
b=b[1];0>f&&(f=a+f+1);0>f&&(f=0);f>this.pages.length-1&&(f=a);0>b&&(b=a+b+1);0>b&&(b=0);b>this.pages.length-1&&(b=a);for(var e=this.opts.firstPageNumber,c=0;c<f;c++)d(".wowbook-page-number",this.pages[c]).remove();for(c=b+1;c<a;c++)d(".wowbook-page-number",this.pages[c]).remove();for(c=f;c<=b;c++)a=d(".wowbook-page-number",this.pages[c]),a.length||(a=d(".wowbook-page-content",this.pages[c]),a=d('<div class="wowbook-page-number"></div>').appendTo(a)),a.html(e++)}},findPagesType:function(){var a=this.opts,
b={},c,f,e;e=a.hardPages||[];var d=!0===e;if(!d){a.hardcovers&&(e.push(0,1,-1),this.pageIsOnTheLeft(this.pages.length-1)&&e.push(-2));a=0;for(f=e.length;a<f;a++)c=e[a],0>c&&(c=this.pages.length+c),0<=c&&c<this.pages.length&&(b[c]=!0)}for(a=this.pages.length;a--;)e=d||b[a]||this.pages[a].hardPageSetByUser,this.pages[a].toggleClass("wowbook-hardpage",e).isHardPage=e},showPage:function(a,b){0>a&&(a=0);a>this.pages.length-1&&(a=this.pages.length-1);for(var c=a-(1-a%2),f=c+1,e=this.pageWidth,g=!1,j,h,
s=0,v=this.pages.length;s<v;s++)j=g?s:v-s,h=this.transparentPages?g?s<=c?"block":"none":s>=f?"block":"none":s===c-2||s===c||s===f||s===f+2?"block":"none",this.pages[s].data("zIndex",j).css({display:h,left:g?0:e,top:0,zIndex:j}),g=!g;c=0<a;f=this.rightPage(a);g=!c;j=!(f&&this.backPage(f.pageIndex));this.leftHandle.toggleClass("wowbook-disabled",g);this.rightHandle.toggleClass("wowbook-disabled",j);this.toggleControl("back",g);this.toggleControl("next",j);this.toggleControl("first",g);this.toggleControl("last",
j);if((g=this.onShowPage)&&d.isFunction(g)&&!this.isOnPage(a))g(this,this.pages[a],a),(j=this.otherPage(a))&&g(this,this.pages[j],j);this.currentPage=a;this.opts.centeredWhenClosed&&this.origin.css("left",c&&f?0:c?e/2:-e/2);this.positionBookShadow();!1!==b&&(this.opts.updateBrowserURL&&this.locationHashToPage()!=a)&&(this.locationHashSetTo=window.location.hash=this.pageToLocationHash(a))},holdPage:function(a,b,c,f,e){"number"===typeof a&&(a=this.pages[a]);if(a){var d=a.data("pageIndex"),j=this.pages.length-
1,h=this.pageIsOnTheLeft(j);if(f){if(!this.corners[f]||(this.pageIsOnTheLeft(d)?/r/:/l/).test(f))return}else f=this.pageIsOnTheLeft(d)?"l":"r";void 0===e&&(e=this.backPage(d));if(e){var s=e.data("pageIndex");if(this.centeredWhenClosed&&(0===d||0===s||h&&(s===j||d===j))){var v=0,l,n=this.pageWidth,q,p,k,m,r,t,u,w;0===d&&(q=-n/2,p=-n/4,k=0,m=-n/2,r=-n,t=p,u=r,w=b);d===j&&h&&(q=n,p=3*n/2,k=n/2,m=0,r=n,t=2*n,u=b,w=t);0===s&&(q=n/2,p=d===j?n:3*n/2,k=d===j?n/2:0,m=-n/2,r=q,t=2*n,u=b,w=t);s===j&&h&&(q=0===
d?0:-n/2,p=n/2,k=n/2,m=0===d?-n/2:0,r=-n,t=p,u=r,w=b);b<q&&(v=k,l=u);b>p&&(v=m,l=w);b>=q&&b<=p&&(b=(b-q)/(p-q),v=k+b*(m-k),l=r+b*(t-r));b=l;this.origin.css("left",v);this.positionBookShadow()}this.zoomed||"basic"==this.pageType(a)||"basic"==this.pageType(e)?this.foldPageBasic(a,b,c,f,e):a.isHardPage||e.isHardPage?this.holdHardpage(a,b,c,f,e):this.foldPage(a,b,c,f,e);if(!a.data("holded")&&(a.addClass("wowbook-page-holded"),e.addClass("wowbook-page-holded"),a.data("holded",!0),this.holdedPage=a,this.holdedPageBack=
e,this.shadows&&this.shadowClipper.css("display","block"),this.clipBoundaries&&this.clipper.css("overflow","visible"),this.positionBookShadow(),this.opts.onHoldPage))this.opts.onHoldPage(this,d,a,e)}}},foldPage:function(a,b,c,d,e){"number"===typeof a&&(a=this.pages[a]);var g=a.data("pageIndex");void 0===e&&(e=this.backPage(g));if(e&&e.length){var j=a.children().first(),g=e.children().first(),h=this.pageWidth,s=this.pageHeight,v=h/2,l=s/2;d||(d="tl");if("l"==d||"r"==d){var n=a.data("grabPoint");n||
(n={x:"l"==d?0:h,y:c},a.data("grabPoint",n));d=(c>=n.y?"t":"b")+d;var q=b-n.x,p=c-n.y,q=Math.atan2(p,q),n={x:0,y:(c>=n.y?0:s)-n.y},n=t(n,2*q);b=n.x+b;c=n.y+c}a.data("holdedAt",{x:b,y:c});a.data("holdedCorner",d);e.css("left",a.css("left"));n=this.corners[d];d=h-n[0];fy=n[1];var q=b-d,p=c-fy,k=Math.sqrt(q*q+p*p);k>h&&(b=d+h*q/k,c=fy+h*p/k);fy=s-fy;q=b-d;p=c-fy;k=Math.sqrt(q*q+p*p);maxdistance=Math.sqrt(h*h+s*s);k>maxdistance&&(b=d+maxdistance*q/k,c=fy+maxdistance*p/k);d=n[0];n=n[1];n==c&&(c=n+0.001);
q=b-d;p=c-n;k=Math.sqrt(q*q+p*p);b=k/2;q=Math.atan2(p,q);p=Math.tan(q);c=q;q=180*q/Math.PI;j.css("transform","rotate("+-q+"deg)");var j={x:d-v,y:l-n},k=t(j,c),m=k.x+b+v+0.5;a.css({clip:"rect(-1000px 2000px 2000px "+m+"px)",transform:"rotate("+q+"deg)"});k=this.calculateOpacity(b,h,this.shadowThreshold,50);if(this.shadows&&0<k){var r=2*Math.sqrt(h*h+s*s),u=-(r-s)/2,y=m+parseFloat(a.css("left"));this.internalShadow.css({display:"block",height:r,transform:"translate("+y+"px,"+u+"px) rotate("+q+"deg)",
transformOrigin:v-m+"px "+(l+(r-s)/2)+"px"});m-=this.foldShadow.width();this.foldShadow.css({display:"block",height:r,transform:"translate("+(m+parseFloat(a.css("left")))+"px,"+u+"px) rotate("+q+"deg)",transformOrigin:v-m+"px "+(l+(r-s)/2)+"px"});this.shadowContainer.css({opacity:k,display:"block"})}else this.shadowContainer.hide();e.show();g.css("transform","rotate("+q+"deg)");j.x=-j.x;k=t(j,-c);m=k.x-b+v-1;e.css({clip:"rect(-1000px 2000px 2000px "+m+"px)",zIndex:1E3,transform:"rotate("+q+"deg)"});
a={x:k.x-b,y:k.y+b*p};j={x:k.x-b,y:k.y-b/(0==p?1E-4:p)};a=t(a,-c);j=t(j,-c);j=-(j.x+v);a=-(a.y-l);e.css({marginLeft:d+j,marginTop:n-a});k=this.calculateOpacity(2*b,2*h,this.foldGradientThreshold,50);this.foldGradient&&0<k?(e=2*Math.sqrt(h*h+s*s),this.foldGradientContainer.appendTo(g),this.foldGradientContainer.css({opacity:k,position:"absolute",left:h-d-this.foldGradientElem.width()/2,top:n-e/2,width:this.foldGradientElem.width(),height:e,transform:"rotate("+-q+"deg)"}),this.foldGradientElem.css({left:-b+
this.foldGradientElem.width()/2,height:e}),this.foldGradientContainer.show()):this.foldGradientContainer.hide()}},holdHardpage:function(a,b,c,f,e){this.clipBoundaries&&this.clipper.children(".wowbook-inner-clipper").css("overflow","visible");"number"===typeof a&&(a=this.pages[a]);var g=a.data("pageIndex"),j=this.pageIsOnTheRight(g),h=this.pageWidth,k=this.pageHeight;void 0===e&&(e=this.backPage(g));if(e&&e.length){f||(f="tl");a.data("holdedAt",{x:b,y:c});a.data("holdedCorner",f);c=j?h-b:b;f=j?0:h;
0>c&&(c=0);c=(g=c<h)?a:e;(g?e:a).css("display","none");a=j!=g;e=b-f;e>h&&(e=h);e<-h&&(e=-h);var l=-Math.sqrt(1600*(1-e*e/((h+15)*(h+15)))),j=Math.abs(e/h),l=1==j?0:Math.atan2(l,e);if(this.opts.use3d&&Modernizr.csstransforms3d){f=g?f:h-f;roty=a?-this._calculateAngleFromX(-e,h):this._calculateAngleFromX(e,h);if(this.animating)if(g=this._animationData,this.curledPage||g.curled){g.curled=!0;if(!g.angle){l={from:roty,to:0};g.angle=l;var m=e+g.dx;l.to=a?-this._calculateAngleFromX(-m,h):this._calculateAngleFromX(m,
h);Math.abs(e)==h&&(l.from=0);Math.abs(m)==h&&(l.to=0);l.delta=l.to-l.from}roty=g.angle.from-g.angle.delta*(g.from.x-b)/g.dx}else Math.abs(b-g.from.x)>Math.abs(g.dx/2)&&(g.angle||(g.angle={from:roty,to:0,delta:-roty,fromx:b,dx:g.to.x-b}),roty=g.angle.from-g.angle.delta*(g.angle.fromx-b)/g.angle.dx);c.css(Modernizr.prefixed("perspectiveOrigin"),"0 50%");c.css({transform:"perspective("+this.opts.perspective+this.perspectiveUnit+") rotate3d(0, 1, 0, "+roty+"deg)",transformOrigin:f+"px 50%",display:"block",
zIndex:1E3})}else c.css({transform:"skewY("+l+"rad) scaleX("+j+")",transformOrigin:(g?f:h-f)+"px 50%",display:"block",zIndex:1E3});!d.wowBook.support.transform&&d.wowBook.support.filters&&(b="M11="+j+", M12=0, M21="+Math.tan(l)*j+", M22=1",c.css("filter","progid:DXImageTransform.Microsoft.Matrix("+b+", sizingMethod='auto expand')"),c.css({marginTop:k-c.height(),marginLeft:a?h-c.width():0}));this.shadows&&this.hardPageShadow.css({display:"block",left:a?0:h,opacity:0.5*Math.abs(e/h)})}},_calculateAngleFromX:function(a,
b,c){c=c||this.opts.perspective;var d=180/Math.PI,e=b*b;c*=c;var g=a*a;a=Math.acos((b*c*a-Math.sqrt(e*e*c*g+e*e*g*g-e*c*g*g))/(e*c+e*g));return-a*d},foldPageBasic:function(a,b,c,d,e){"number"===typeof a&&(a=this.pages[a]);var g=a.data("pageIndex"),j=this.pageIsOnTheRight(g),h=!j;void 0===e&&(e=this.backPage(g));if(e&&e.length){var g=this.pageWidth,k=this.pageHeight,l=this.foldGradientElem.width(),m=this.foldShadow.width();d||(d="tl");if(!a.data("foldPageBasic")){a.data("foldPageBasic",!0);this.internalShadow.css("display",
"none");this.foldShadow.css({display:"none",height:k,transform:"",top:0}).toggleClass("wowbook-shadow-fold-flipped",j);this.shadowContainer.css("display","block");var n=e.children().first();this.foldGradientContainer.appendTo(n).css({width:l,height:k,top:0,transform:"",zIndex:1E9});this.foldGradientElem.css({left:0,height:k}).toggleClass("wowbook-fold-gradient-flipped",j)}a.data("holdedAt",{x:b,y:c});a.data("holdedCorner",d);j=h?b:g-b;0>j&&(j=0);j>2*g&&(j=2*g);b=j/2;h?(c="rect(-1000px 1000px 1000px "+
b+"px)",d="rect(-1000px 1000px 1000px "+(g-b)+"px)",j-=g):(c="rect(-1000px "+(g-b)+"px 1000px -1000px)",d="rect(-1000px "+b+"px 1000px -1000px)",j=g-j+g);a.css("clip",c);e.css({clip:d,left:j,zIndex:1E3,display:"block"});a=this.calculateOpacity(2*b,2*g,this.shadowThreshold,50);this.shadows&&0<a?(e=h?b-m:g-b+g,this.shadowContainer.css("opacity",a),this.foldShadow.css({left:e,display:"block"})):this.foldShadow.css("display","none");a=this.calculateOpacity(2*b,2*g,this.foldGradientThreshold,50);this.foldGradient&&
0<a?this.foldGradientContainer.css({opacity:a,left:h?g-b:b-l,display:"block"}):this.foldGradientContainer.css("display","none")}},animateFoldPage:function(a,b,c,f,e,g,j,h){var k=this;if(!k.animating){k.animating=!0;c||(c=a.data("holdedAt"));b||(b=a.data("holdedCorner"));var l=c.x-f.x,m=c.y-f.y,n,q;void 0==h&&(h=this.turnPageDuration*Math.abs(l)/(2*this.pageWidth));h<this.opts.turnPageDurationMin&&(h=this.opts.turnPageDurationMin);!a.isHardPage&&0.4<h/this.turnPageDuration&&this.playFlipSound();this._animationData=
{from:c,to:f,dx:-l};this.holdPage(a,c.x,c.y,b,j);this._percent=0;d(this).animate({_percent:1},{duration:h,easing:"linear",complete:function(){k.animating=!1;d.isFunction(e)&&e()},step:function(d){n=c.x-d*l;q=c.y-d*m;g&&(q-=(0.5-Math.abs(0.5-d))*k.pageHeight/10);k.holdPage(a,n,q,b,j)}})}},stopAnimation:function(a){arguments.length||(a=!0);d(this).stop(!0,a);this.animating=!1},releasePages:function(){for(var a=0,b=this.pages.length;a<b;a++)this.pages[a].data("holded")&&this.releasePage(a)},releasePage:function(a,
b,c,d){"number"===typeof a&&(a=this.pages[a]);var e=this,g=a.data("holdedAt"),j=a.data("holdedCorner");if(b&&g)this.animateFoldPage(a,j,g,{x:this.corners[j][0],y:this.corners[j][1]},function(){e.releasePage(a,!1,c)},!1,c,d);else if(b=a.data("pageIndex"),void 0===c&&(c=this.holdedPageBack||this.backPage(b)),this.holdedPageBack=this.holdedPage=null,a.data({holdedAt:null,holdedCorner:null,grabPoint:!1,foldPageBasic:null,holded:!1}),this.clipBoundaries&&!this.zoomed&&(this.clipper.css("overflow","hidden"),
this.clipper.children(".wowbook-inner-clipper").css("overflow","hidden")),this.shadowClipper.css("display","none"),this.internalShadow.parent().hide(),this.foldGradientContainer.hide(),this.hardPageShadow.hide(),this.resetPage(a),c&&c.length&&(this.resetPage(c),c.hide()),this.foldShadow.removeClass("wowbook-shadow-fold-flipped").css({transform:"",left:""}),this.foldGradientElem.removeClass("wowbook-fold-gradient-flipped").css("transform",""),this.foldGradientContainer.css("transform","").appendTo(this.pagesContainer),
this.positionBookShadow(),this.opts.onReleasePage)this.opts.onReleasePage(this,b,a,c)},resetPage:function(a){a.removeClass("wowbook-page-holded");this.resetCSS||(this.resetCSS={transform:"",transformOrigin:"",clip:"auto",marginLeft:0,marginTop:0,filter:""});var b=this.pageWidth,c=this.pageHeight;a.css(this.resetCSS).css({zIndex:a.data("zIndex"),width:b,height:c,left:this.pageIsOnTheLeft(a.data("pageIndex"))?0:b});d.browser.msie&&9>d.browser.version&&a.attr("style",a.attr("style").replace(/clip\: [^;]+;/i,
""));a=d(".wowbook-page-content",a);a.css(this.resetCSS);k(a,b,c)},gotoPage:function(a,b){if(!this.animating&&("string"===typeof a&&"#"==a.charAt(0)&&(a=this.selectorToPage(a)),0>a&&(a=0),a>this.pages.length-1&&(a=this.pages.length-1),!this.isOnPage(a))){var c=a<this.currentPage,d=this,e=c?d.leftPage():d.rightPage();if(e){this.uncurl(!0);var g,j;c?(g=this.leftPage(a),j=this.rightPage(a)):(g=this.rightPage(a),j=this.leftPage(a));if(c)for(var h=e.pageIndex-1;0<=h;h--)this.pages[h].css("display","none");
else for(var h=e.pageIndex+1,k=this.pages.length;h<k;h++)this.pages[h].css("display","none");g&&g.css("display","block");var l=a;g=e.data("holdedAt");h=e.data("holdedAt");k=e.data("holdedCorner")||(c?"tl":"tr");c?(h=h||{x:0,y:0},c={x:2*d.pageWidth,y:"bl"!=k?0:this.pageHeight}):(h=h||{x:this.pageWidth,y:0},c={x:-d.pageWidth,y:"br"!=k?0:this.pageHeight});d.animateFoldPage(e,k,h,c,function(){d.releasePage(e,!1,j);d.showPage(l,b)},!g,j);return a}}},back:function(){return this.gotoPage(this.currentPage-
2)},advance:function(){return this.gotoPage(this.currentPage+2)},leftPage:function(a){a=void 0!==a?a:this.currentPage;this.pageIsOnTheRight(a)&&a--;return this.pages[a]||null},rightPage:function(a){a=void 0!==a?a:this.currentPage;this.pageIsOnTheLeft(a)&&a++;return this.pages[a]||null},pageIsOnTheRight:function(a){return!(a%2)},pageIsOnTheLeft:function(a){return!!(a%2)},otherPage:function(a){a+=this.pageIsOnTheRight(a)?-1:1;if(0>a||a>this.pages.length-1)a=null;return a},isOnPage:function(a){return"number"===
typeof a&&(a===this.currentPage||a===this.otherPage(this.currentPage))},backPage:function(a){a+=this.pageIsOnTheRight(a)?1:-1;return this.pages[a]},pageType:function(a){a="number"===typeof a?this.pages[a]:a;return a.isHardPage?"hard":a.find(".wowbook-page-content.wowbook-basic-page").length?"basic":"soft"},calculateOpacity:function(a,b,c,d){if(a<=c||a>=b-c)return 0;if(a>=d&&a<=b-d)return 1;a>d&&(a=b-a);return(a-c)/(d-c)},startSlideShow:function(){this.slideShowRunning=!0;this.advanceAfterTimeout(this.slideShowDelay);
d(this.opts.controls.slideShow).addClass("wowbook-disabled")},advanceAfterTimeout:function(a){var b=this;this.slideShowTimer=setTimeout(function(){b.animating||b.holdedPage?b.advanceAfterTimeout(100):(b.advance(),b.isOnPage(b.pages.length-1)?b.stopSlideShow():b.advanceAfterTimeout(b.slideShowDelay+b.turnPageDuration))},a)},stopSlideShow:function(){clearTimeout(this.slideShowTimer);this.slideShowTimer=void 0;this.slideShowRunning=!1;d(this.opts.controls.slideShow).removeClass("wowbook-disabled")},
toggleSlideShow:function(){this.slideShowRunning?this.stopSlideShow():this.startSlideShow()},findSections:function(a){a&&(this.sectionDefinition=a);var b=this.sectionDefinition;a=[];var c;"string"===typeof b&&(c=b,b=[],d(c,this.elem).each(function(a,c){b.push(["#"+c.id,d(c).html()])}));if(d.isArray(b)){for(var f=0,e=b.length;f<e;f++){c=b[f];if("string"===typeof c)try{c=[c,d(c,this.elem).html()]}catch(g){continue}try{c[2]=this.selectorToPage(c[0])}catch(j){continue}void 0!==c[2]&&a.push({id:c[0],title:c[1],
page:c[2]})}a=a.sort(function(a,b){return a.page-b.page})}return this.sections=a},pageToSection:function(a){for(var b=this.sections,c,d=0,e=b.length;d<e&&!(b[d].page>a);d++)c=b[d];return c},currentSection:function(){return this.pageToSection(this.currentPage)},fillToc:function(a,b){var c=d(a||this.opts.toc),f,e,g="";if(0!==c.length){f=this.sections;"undefined"===typeof b&&(b=this.opts.tocTemplate);b||(g=c.is("UL, OL")?"<li>":"<div>",b='<a href="${link}">${section}</a>');for(var j=0,h=f.length;j<h;j++)e=
f[j],e=b.replace(/\$\{link\}/g,"#"+this.id+"/"+e.id.substr(1)).replace(/\$\{section\}/g,e.title).replace(/\$\{page\}/g,e.page),d(e).appendTo(c).wrap(g)}},locationHashToPage:function(a){void 0===a&&(a=window.location.hash);if(a=="#"+this.id+"/")return 0;a=a.slice(1).split("/");if(a[0]===this.id){if(1===a.length)return 0;var b=parseInt(a[1]);if(!isNaN(b))return Math.max(b-1,0);b=this.selectorToPage("#"+a[1]);if(void 0===b)return 0;isNaN(a[2])||(b+=Math.max(parseInt(a[2])-1,0));return+b}},pageToLocationHash:function(a){var b=
"",c=a+1;if(a=this.pageToSection(a))b+="/"+a.id.replace("#",""),c-=a.page;1<c&&(b+="/"+c);return"#"+this.id+(b||"/")},selectorToPage:function(a){a=d(a,this.elem).closest(".wowbook-page");if(a.length)return+a.data("pageIndex")},getLocationHash:function(){return window.location.hash.slice(1)},locationEndsInHash:function(a){void 0===a&&(a=window.location.href);return a.lastIndexOf("#")==a.length-1},zoom:function(a){for(var b=0,c=this.pages.length;b<c;b++)if(this.pages[b].data("holdedAt"))return;a<this.zoomMin&&
(a=this.zoomMin);a>this.zoomMax&&(a=this.zoomMax);if(a!==this.zoomLevel){this.zoomLevel=a;var f=this,b=this.zoomWindow,c=this.zoomContent,e=d(this.zoomBoundingBox),g=a,j=2*f.pageWidth*g,g=f.pageHeight*g,h=e.width(),k=e.height(),l=Math.min(j,h),m=Math.min(g,k),n=(2*this.pageWidth-l)/2,q=(this.pageHeight-m)/2;b.css({width:l,height:m,left:n,top:q});this.zoomContentOverflowed=j>h||g>k;var p=b.offset(),e=e[0]!==window?e.offset():{left:e.scrollLeft(),top:e.scrollTop()};p.right=p.left+l;p.bottom=p.top+m;
e.right=e.left+h;e.bottom=e.top+k;p.left<e.left&&b.css("left",n+(e.left-p.left));p.right>e.right&&b.css("left",n+(e.right-p.right));p.top<e.top&&b.css("top",q+(e.top-p.top));p.bottom>e.bottom&&b.css("top",q+(e.bottom-p.bottom));p=b.offset();e=c.offset();p.right=p.left+l;p.bottom=p.top+m;e.right=e.left+j;e.bottom=e.top+g;e.left>p.left&&c.css("marginLeft",0);e.right<p.right&&c.css("marginLeft",(parseFloat(c.css("marginLeft"))||0)+(p.right-e.right));e.top>p.top&&c.css("marginTop",0);e.bottom<p.bottom&&
c.css("marginTop",(parseFloat(c.css("marginTop"))||0)+(p.bottom-e.bottom));l===j&&c.css("marginLeft",0);m===g&&c.css("marginTop",0);d.wowBook.support.transform?c.css({transform:"scale("+a+")",transformOrigin:"0 0"}):c.css("zoom",a);1===this.zoomLevel?(b.unbind("mousemove.wowbook").css({overflow:"visible",left:0,top:0}),this.clipBoundaries&&this.clipper.css("overflow","hidden"),c.css({marginLeft:0,marginTop:0})):(this.clipBoundaries&&this.clipper.css("overflow","visible"),b.css("overflow","hidden"),
this.zoomed||b.bind("mousemove.wowbook",function(a){f.zoomedAt(a)}));this.zoomed=1!==a;this.positionBookShadow();if(this.onZoom)this.onZoom(this);this.toggleControl("zoomIn",this.zoomLevel==this.zoomMax);this.toggleControl("zoomOut",this.zoomLevel==this.zoomMin)}},zoomIn:function(a){this.zoom(this.zoomLevel+(a||this.zoomStep))},zoomOut:function(a){this.zoom(this.zoomLevel-(a||this.zoomStep))},zoomedAt:function(a){if(this.zoomContentOverflowed){var b=this.zoomLevel,c=this.zoomWindow.offset(),f=a.pageX-
c.left;a=a.pageY-c.top;var e=this.zoomWindow.width(),c=2*this.pageWidth*b-e,f=f/e,e=this.zoomWindow.height(),g=this.pageHeight*b-e;adjust=d.browser.ie8mode?b:1;this.zoomContent.css({marginLeft:-c*f/adjust,marginTop:-g*(a/e)/adjust})}},positionBookShadow:function(){var a=this.pages.length,b=!(!this.opts.bookShadow||this.zoomed||!a||3>a&&this.holdedPage);this.bookShadow.toggle(b);if(b){var b=this.pageWidth,c=this.currentPage,d=this.holdedPageBack&&this.holdedPageBack.pageIndex,e=d&&this.pageIsOnTheLeft(d),
c=0<c,g=this.rightPage(),c=!c||0===d,a=!g||d===a-1&&e,d=c!=a;c&&a?this.bookShadow.hide():this.bookShadow.css({left:(c?b:0)+this.pagesContainer.position().left,width:d?b:2*b})}},playFlipSound:function(){if(this.flipSound){var a=this.opts.onPlayFlipSound;d.isFunction(a)&&!1===a(this)||(this.audio||(this.audio=this.createAudioPlayer()),this.audio&&this.audio.play&&this.audio.play())}},toggleFlipSound:function(a){arguments.length||(a=!this.flipSound);this.flipSound=a;this.toggleControl("flipSound",!a)},
createAudioPlayer:function(a,b){a||(a=this.opts.flipSoundPath);b||(b=this.opts.flipSoundFile);for(var c=[],f=0,e=b.length;f<e;f++)c.push('<source src="'+a+b[f]+'">');return d("<audio preload>"+c.join("")+"</audio>")[0]},_untouch:function(a){return a.originalEvent.touches&&a.originalEvent.touches[0]||a},touchSupport:function(){var a=this;a.elem.bind("touchstart",function(b){var c=b.originalEvent.touches;1<c.length||(a._touchStarted={x:c[0].pageX,y:c[0].pageY,timestamp:b.originalEvent.timeStamp,inHandle:d(b.target).hasClass("wowbook-handle")},
a._touchStarted.inHandle&&a.pageEdgeDragStart(a._untouch(b)))});d(document).bind("touchmove",function(b){if(a._touchStarted){var c=b.originalEvent.touches;a._touchEnded={x:c[0].pageX,y:c[0].pageY,timestamp:b.originalEvent.timeStamp};if(a._touchStarted.inHandle)return a.pageEdgeDrag(a._untouch(b));20<Math.abs(a._touchEnded.x-a._touchStarted.x)&&b.preventDefault();b.preventDefault()}});d(document).bind("touchend touchcancel",function(b){if(a._touchStarted){!a._touchEnded&&d(b.target).hasClass("wowbook-handle")&&
(b=d(b.target).data("corner"),"r"===b&&a.advance(),"l"===b&&a.back());var c=a._touchStarted,f=a._touchEnded||a._touchStarted;a._touchStarted=null;a._touchEnded=null;if(c.inHandle)return a.pageEdgeDragStop({pageX:f.x}),!1;b=f.x-c.x;var e=f.y-c.y,c=f.timestamp-c.timestamp;if(!(20>Math.abs(b)||200<c)&&Math.abs(b)>Math.abs(e))return 0>b?a.advance():a.back(),!1}})},pageEdgeDragStart:function(a){if(this.animating&&!this.curledPage||this.zoomed||!d(a.target).hasClass("wowbook-handle"))return!1;var b=this,
c=b.elem.offset();b.mouseDownAtLeft=a.pageX-c.left<b.pageWidth;b.pageGrabbed=b.mouseDownAtLeft?b.leftPage():b.rightPage();if(!b.pageGrabbed)return!1;this.uncurl(!0);b.pageGrabbedOffset=b.pageGrabbed.offset();this.holdPage(this.pageGrabbed,a.pageX-this.pageGrabbedOffset.left,a.pageY-this.pageGrabbedOffset.top);d(document).bind("mousemove.wowbook",function(a){return b.pageEdgeDrag(a)}).bind("mouseup.wowbook",function(a){return b.pageEdgeDragStop(a)});return!1},pageEdgeDrag:function(a){this.holdPage(this.pageGrabbed,
a.pageX-this.pageGrabbedOffset.left,a.pageY-this.pageGrabbedOffset.top);return!1},pageEdgeDragStop:function(a){var b=this.elem.offset();a=a.pageX-b.left<this.pageWidth;this.mouseDownAtLeft&&!a?this.back():!this.mouseDownAtLeft&&a?this.advance():this.releasePage(this.pageGrabbed,!0);d(document).unbind(".wowbook")},curl:function(a,b){if(!this.curledPage&&!this.holdedPage){void 0==a&&(a=this.currentPage);if("number"==typeof a||"string"==typeof a)a=this.pages[+a];if(a&&!a.isCurled){a.isCurled=!0;this.curledPage=
a;var c=this.pageIsOnTheLeft(a.pageIndex),d=c?0:this.pageWidth,e=!b?2:this.pageHeight-1;this.animateFoldPage(a,(b?"b":"t")+(c?"l":"r"),{x:d,y:e},{x:d+this.opts.curlSize*(c?1:-1),y:e+this.opts.curlSize*(!b?1:-1)},null,!1,void 0,400)}}},uncurl:function(a,b){if(this.curledPage){!0==a&&(b=!0,a=void 0);void 0==a&&(a=this.curledPage||this.currentPage);if("number"==typeof a||"string"==typeof a)a=this.pages[+a];a.isCurled&&(this.stopAnimation(!1),this.releasePage(a,!b,void 0,400),a.isCurled=!1,this.curledPage=
null)}},initThumbnails:function(){this.thumbnails=[];this.thumbnailsContainer=d("<div class='wowbook-thumbnails'>").append("<div class='wowbook-wrapper'><div class='wowbook-back wowbook-button' /><div class='wowbook-clipper'><ul></ul></div><div class='wowbook-next wowbook-button' /></div>").css("display","none").css("transform","translateZ(0)").appendTo(d(this.opts.thumbnailsParent));this.thumbnailsList=this.thumbnailsContainer.find("ul");this.opts.thumbnailsContainerWidth&&this.thumbnailsContainer.width(this.opts.thumbnailsContainerWidth);
this.opts.thumbnailsContainerHeight&&this.thumbnailsContainer.height(this.opts.thumbnailsContainerHeight);var a=this.opts.thumbnailsPosition;if("left"==a||"right"==a)this.opts.thumbnailsVertical=!0,"right"==a&&this.thumbnailsContainer.css({position:"absolute",left:"auto",right:"0px"});if("top"==a||"bottom"==a)this.opts.thumbnailsVertical=!1,"bottom"==a&&this.thumbnailsContainer.css({position:"absolute",top:"auto",bottom:"0px"});this.thumbnailsContainer.addClass(this.opts.thumbnailsVertical?"wowbook-vertical":
"wowbook-horizontal");var b=this,c=(a=this.opts.thumbnailsVertical)?"top":"left",f=a?"height":"width",e={};this.thumbnailsContainer.find(".wowbook-back.wowbook-button").click(function(){var a=b.thumbnailsList.position()[c]+b.thumbnailsList.parent()[f]();0<a&&(a=0);e[c]=a;b.thumbnailsList.animate(e,"fast")});this.thumbnailsContainer.find(".wowbook-next.wowbook-button").click(function(){var a=b.thumbnailsList.parent()[f](),d=b.thumbnailsList.position(),h=-b.thumbnailsList[f]()+a,a=d[c]-a;a<h&&(a=h);
e[c]=a;b.thumbnailsList.animate(e,"fast")});this.thumbnailsContainer.find(".wowbook-clipper").css("transform","translateZ(0)")},destroyThumbnails:function(){this.thumbnailsContainer&&this.thumbnailsContainer.remove();this.thumbnails=this.thumbnailsContainer=null},createThumbnails:function(){this.thumbnails||this.initThumbnails();var a,b=this.thumbnailConfig();this.thumbnails=[];for(var c=0,d=this.pages.length;c<d;c++)a=this.createThumbnail(c,b),this.thumbnailsList.append(a),this.thumbnails.push(a);
a=this.thumbnailsContainer;a.width()||a.width(2*b.width)},thumbnailConfig:function(){var a={},b=d('<div class="wowbook-thumbnail" style="display:none;position:absolute;line-height:0px;font-size:0px;">').prependTo(this.thumbnailsContainer),c=this.opts.thumbnailHeight||(2>=b.height()?0:b.height()),f=this.opts.thumbnailWidth||b.width(),e=f/this.pageWidth||c/this.pageHeight||this.opts.thumbnailScale;b.remove();a.width=f||this.pageWidth*e;a.height=c||this.pageHeight*e;a.cloneCSS={display:"block",left:0,
top:0,position:"relative",transformOrigin:"0 0"};d.wowBook.support.transform?a.cloneCSS.transform="scale("+e+")":a.cloneCSS.zoom=e;return a},createThumbnail:function(a,b){var c=this.pages[a];if(c){b||(b=this.thumbnailConfig());var f=d('<li class="wowbook-thumbnail"><div class="wowbook-overlay">').addClass(this.pageIsOnTheLeft(a)?"wowbook-left":"wowbook-right").css({width:b.width,height:b.height});this.opts.thumbnailsSprite?f.css("background","url("+this.opts.thumbnailsSprite+") no-repeat 0px -"+a*
b.height+"px"):(c=c.clone(),c.hasClass("wowbook-page-holded")&&(this.resetPage(c),c.find(".wowbook-fold-gradient-container").remove()),c.css(b.cloneCSS),f.prepend(c));var e=this;f.click(function(){e.gotoPage(a)});return f}},updateThumbnail:function(a){var b=this.thumbnails[a];if(b&&(a=this.createThumbnail(a)))this.opts.thumbnailsSprite||b.children(":not(.wowbook-overlay)").replaceWith(a.children(":not(.wowbook-overlay)")),b.width(a.width()),b.height(a.height())},showThumbnails:function(){(!this.thumbnails||
!this.thumbnails.length)&&this.createThumbnails();this.thumbnailsContainer.fadeIn()},hideThumbnails:function(){this.thumbnailsContainer.fadeOut()},toggleThumbnails:function(){d(this.thumbnailsContainer).is(":visible")?this.hideThumbnails():this.showThumbnails()},controllify:function(a){var b=this;d(a.zoomIn).click(function(){b.zoomIn();return!1});d(a.zoomOut).click(function(){b.zoomOut();return!1});d(a.next).click(function(){b.advance();return!1});d(a.back).click(function(){b.back();return!1});d(a.first).click(function(){b.gotoPage(0);
return!1});d(a.last).click(function(){b.gotoPage(b.pages.length-1);return!1});d(a.slideShow).click(function(){b.toggleSlideShow();return!1});d(a.flipSound).click(function(){b.toggleFlipSound();return!1});d(a.thumbnails).click(function(){b.toggleThumbnails();return!1})},toggleControl:function(a,b){(a=this.opts.controls[a])&&d(a).toggleClass("wowbook-disabled",b)}};d.wowBook.defaults={width:500,height:300,startPage:0,hardcovers:!1,hardPages:!1,centeredWhenClosed:!1,transparentPages:!1,use3d:!0,perspective:2E3,
bookShadow:!0,gutterShadow:!0,shadowThreshold:20,shadows:!0,foldGradient:!0,foldGradientThreshold:20,pageNumbers:!0,firstPageNumber:1,numberedPages:!1,deepLinking:!0,updateBrowserURL:!0,curl:!0,curlSize:40,slideShow:!1,slideShowDelay:1E3,pauseOnHover:!0,mouseWheel:!1,handleWidth:!1,handleClickDuration:300,turnPageDuration:1E3,turnPageDurationMin:300,forceBasicPage:!1,sections:".wowbook-section",zoomLevel:1,zoomMax:2,zoomMin:1,zoomBoundingBox:window,zoomStep:0.05,onZoom:null,flipSound:!0,flipSoundFile:["page-flip.mp3",
"page-flip.ogg"],flipSoundPath:"./wow_book/sound/",onPlayFlipSound:null,keyboardNavigation:{back:37,advance:39},clipBoundaries:!0,controls:{},onShowPage:null,onHoldPage:null,onReleasePage:null,thumbnails:!1,thumbnailsParent:"body",thumbnailScale:0.2,thumbnailWidth:null,thumbnailHeight:null,thumbnailsPosition:null,thumbnailsVertical:!0,thumbnailsContainerWidth:null,thumbnailsContainerHeight:null,thumbnailsSprite:null};"undefined"!=typeof QUnit&&(d.wowBook.wowBook=r);d.browser.ie8mode=d.browser.msie&&
8==document.documentMode;var l=d.browser.msie&&9>d.browser.version?1:0,m={thin:2-l,medium:4-l,thick:6-l}})(jQuery);
(function(d){function r(k){var l=k||window.event,m=[].slice.call(arguments,1),a=0,b=0,c=0;k=d.event.fix(l);k.type="mousewheel";l.wheelDelta&&(a=l.wheelDelta/120);l.detail&&(a=-l.detail/3);c=a;void 0!==l.axis&&l.axis===l.HORIZONTAL_AXIS&&(c=0,b=-1*a);void 0!==l.wheelDeltaY&&(c=l.wheelDeltaY/120);void 0!==l.wheelDeltaX&&(b=-1*l.wheelDeltaX/120);m.unshift(k,a,b,c);return(d.event.dispatch||d.event.handle).apply(this,m)}var t=["DOMMouseScroll","mousewheel"];if(d.event.fixHooks)for(var u=t.length;u;)d.event.fixHooks[t[--u]]=
d.event.mouseHooks;d.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var d=t.length;d;)this.addEventListener(t[--d],r,!1);else this.onmousewheel=r},teardown:function(){if(this.removeEventListener)for(var d=t.length;d;)this.removeEventListener(t[--d],r,!1);else this.onmousewheel=null}};d.fn.extend({mousewheel:function(d){return d?this.bind("mousewheel",d):this.trigger("mousewheel")},unmousewheel:function(d){return this.unbind("mousewheel",d)}})})(jQuery);
(function(d){function r(k){if(k in t.style)return d.wowBook.support[k]=k;for(var l=u.length,m,a=k.charAt(0).toUpperCase()+k.substr(1);l--;)if(m=u[l]+a,m in t.style)return d.wowBook.support[k]=m}if(d.cssHooks){var t=document.createElement("div"),u=["O","ms","Webkit","Moz"];r("transform");r("transformOrigin");r("boxSizing");d.wowBook.support.boxSizing&&8>document.documentMode&&(d.wowBook.support.boxSizing=!1);t=null;d.each(["transform","transformOrigin"],function(k,l){d.wowBook.support[l]&&(d.wowBook.support[l]!==
l&&!d.cssHooks[l])&&(d.cssHooks[l]={get:function(k){return d.css(k,d.wowBook.support[l])},set:function(k,a){k.style[d.wowBook.support[l]]=a}})});d.wowBook.applyAlphaImageLoader=function(k){var l,m,a,b,c="",f=d("<div style='display:none'></div>").appendTo("body");m=0;for(a=k.length;m<a;m++)if(b=k[m],f.addClass(b),l=f.css("background-image").match(/^url\("(.*)"\)$/))c+="."+b+"{background:none; filter : progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+l[1]+"', sizingMethod='scale'); } ",f.removeClass(b);
d("body").append("<style>"+c+"</style>")}}else alert("jQuery 1.4.3+ is needed for this plugin to work")})(jQuery);